//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> RecieveDate { get; set; }
        public Nullable<bool> Payment { get; set; }
        public string Note { get; set; }
        public Nullable<double> ShippingCost { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<bool> CheckOut { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
