//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ReceiptID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<bool> Payment { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
